version: "3.2"
services:
  mysql:
    image: mysql:5.5
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=helloWorld
      - MYSQL_DATABASE=jpetstore
      - MYSQL_USER=jpetstore
      - MYSQL_PASSWORD=jppwd
    networks:
      - test-net

  tomcat:
    image: tomcat:7.0
    ports:
      - 8888:8080
    networks:
      - test-net

networks:
  test-net:
    driver: bridge

volumes:
  mysql: